/**
 * Project and direction types for dynamic AI-directed video generation
 */

import type { ProjectConfig } from './providers';

/**
 * Video style presets that influence the AI director's decisions
 */
export type VideoStyle =
  | 'cinematic'
  | 'minimal'
  | 'energetic'
  | 'documentary'
  | 'dramatic'
  | 'playful'
  | 'corporate'
  | 'artistic';

/**
 * Camera movement types for shot direction
 */
export type CameraMove =
  | 'static'
  | 'push_in'
  | 'pull_out'
  | 'pan_left'
  | 'pan_right'
  | 'tilt_up'
  | 'tilt_down'
  | 'crane_up'
  | 'crane_down'
  | 'dolly_left'
  | 'dolly_right';

/**
 * Transition types between shots
 */
export type TransitionType =
  | 'cut'
  | 'crossfade'
  | 'fade_black'
  | 'fade_white'
  | 'wipe_left'
  | 'wipe_right';

/**
 * Cost estimate breakdown for a video project
 */
export interface CostEstimate {
  /** Estimated LLM cost (direction + refinement) */
  llm: number;
  /** Estimated image generation cost */
  images: number;
  /** Estimated video generation cost */
  videos: number;
  /** Estimated compilation cost */
  compile: number;
  /** Total estimated cost */
  total: number;
  /** Detailed breakdown */
  breakdown: {
    /** Number of images to generate */
    imageCount: number;
    /** Number of videos to generate */
    videoCount: number;
    /** Total video duration in seconds */
    totalDuration: number;
  };
}

/**
 * Individual shot within a scene
 * Contains all information needed to generate start/end frames and video
 */
export interface DirectedShot {
  /** Shot ID (unique within scene) */
  id: number;
  /** Shot duration in seconds (5-10) */
  duration: number;

  // Image prompts
  /** Detailed prompt for the start frame */
  startPrompt: string;
  /** Detailed prompt for the end frame */
  endPrompt: string;

  // Video generation
  /** Description of motion/action between frames */
  motionPrompt: string;
  /** Camera movement for this shot */
  cameraMove: CameraMove;

  // Style
  /** Lighting description for this shot */
  lighting: string;
  /** Color palette (optional) */
  colorPalette?: string;

  // Continuity
  /** Transition effect at start of shot */
  transitionIn?: TransitionType;
  /** Transition effect at end of shot */
  transitionOut?: TransitionType;
}

/**
 * Scene grouping related shots
 * A scene represents a coherent segment of the video
 */
export interface DirectedScene {
  /** Scene ID (unique within project) */
  id: number;
  /** Scene name */
  name: string;
  /** Description of what happens in this scene */
  description: string;
  /** Emotional tone/mood of the scene */
  mood: string;
  /** Shots that make up this scene */
  shots: DirectedShot[];
}

/**
 * Complete video direction generated by AI Director
 * This is the output of the direction phase
 */
export interface VideoDirection {
  /** Video title */
  title: string;
  /** Narrative description of the complete video */
  narrative: string;
  /** Total duration in seconds */
  totalDuration: number;
  /** Scenes that make up the video */
  scenes: DirectedScene[];
  /** Estimated costs for this direction */
  estimatedCost: CostEstimate;
}

/**
 * Main project interface
 * Represents a video project from concept to completion
 */
export interface Project {
  /** Unique project identifier */
  id: string;
  /** Project name */
  name: string;

  // User input
  /** Video concept/idea from the user */
  concept: string;
  /** Desired visual style (optional) */
  style?: VideoStyle;
  /** Target duration in seconds */
  targetDuration: number;
  /** Video aspect ratio */
  aspectRatio: '16:9' | '9:16' | '1:1';

  // Provider configuration (BYOK)
  /** Provider configuration with API keys */
  config: ProjectConfig;

  // LLM-generated structure (after direction phase)
  /** Video direction (null until directed) */
  direction?: VideoDirection;

  // Metadata
  /** Project creation timestamp */
  createdAt: string;
  /** Last update timestamp */
  updatedAt: string;
}

/**
 * Input for the AI Director
 */
export interface DirectorInput {
  /** Video concept description */
  concept: string;
  /** Desired video style */
  style?: VideoStyle;
  /** Target duration in seconds */
  targetDuration: number;
  /** Aspect ratio */
  aspectRatio: '16:9' | '9:16' | '1:1';
  /** Optional constraints for direction */
  constraints?: {
    /** Maximum number of scenes */
    maxScenes?: number;
    /** Maximum shots per scene */
    maxShotsPerScene?: number;
    /** Elements that must be included */
    mustInclude?: string[];
    /** Elements to avoid */
    avoid?: string[];
  };
}
