/**
 * Type definitions for AI Director module
 */

export type VideoStyle =
  | 'cinematic'
  | 'minimal'
  | 'energetic'
  | 'documentary'
  | 'dramatic'
  | 'playful'
  | 'corporate'
  | 'artistic';

export type CameraMove =
  | 'static'
  | 'push_in'
  | 'pull_out'
  | 'pan_left'
  | 'pan_right'
  | 'tilt_up'
  | 'tilt_down'
  | 'crane_up'
  | 'crane_down'
  | 'dolly_left'
  | 'dolly_right';

export type TransitionType =
  | 'cut'
  | 'crossfade'
  | 'fade_black'
  | 'fade_white'
  | 'wipe_left'
  | 'wipe_right';

/**
 * A single shot within a scene
 */
export interface DirectedShot {
  id: number;
  duration: number; // 5-10 seconds

  // Image prompts
  startPrompt: string;
  endPrompt: string;

  // Video generation
  motionPrompt: string;
  cameraMove: CameraMove;

  // Style
  lighting: string;
  colorPalette?: string;

  // Continuity
  transitionIn?: TransitionType;
  transitionOut?: TransitionType;
}

/**
 * A scene containing one or more shots
 */
export interface DirectedScene {
  id: number;
  name: string;
  description: string;
  mood: string;
  shots: DirectedShot[];
}

/**
 * Cost estimate breakdown
 */
export interface CostEstimate {
  llm: number;
  images: number;
  videos: number;
  compile: number;
  total: number;
  breakdown: {
    imageCount: number;
    videoCount: number;
    totalDuration: number;
  };
}

/**
 * Complete video direction generated by AI Director
 */
export interface VideoDirection {
  title: string;
  narrative: string;
  totalDuration: number;
  scenes: DirectedScene[];
  estimatedCost?: CostEstimate;
}

/**
 * Input to AI Director
 */
export interface DirectorInput {
  concept: string;
  style?: VideoStyle;
  targetDuration: number;
  aspectRatio: '16:9' | '9:16' | '1:1';
  constraints?: {
    maxScenes?: number;
    maxShotsPerScene?: number;
    mustInclude?: string[];
    avoid?: string[];
  };
}

/**
 * Feedback for refining a direction
 */
export interface DirectorFeedback {
  direction: VideoDirection;
  feedback: string;
}
